### PR TITLE
Add methalox config

### PR DESCRIPTION
**Pull request by dgeastman**

### CODE REVIEW

**Comment by Tyaedalis** [comment]
I gotta know, what's with the PNG's?

**Comment by dgeastman** [comment]
I don't see them.  I was originally taking screenshots of the results before I started using your python script, but I thought I deleted them.  Where do you see them?

**Comment by Tyaedalis** [comment]
Oh, I saw only the remnants of them from your git ignore. BTW, I'm gonna
update the script fairly substantially over the next couple days to add
archiving of all data in a nice way, since I need to redo *everything* now.
It will keep all data generated in a nice format for later.

**Comment by Tyaedalis** [comment]
If you could send me any data files you still have (looks like you saved yours; smart!) I will add those to said archive.

**Comment by dgeastman** [comment]
The zip with all my data is included in the commit, so you should just be able to grab it here.

**Comment by Tyaedalis** [comment]
Oh, sweet.

**Comment by ferram4** [comment]
Alright, this LGTM.

**Pull request merged**
